"""
extend_depot_cost_table.jl

Extends the existing cost table with depot↔sat entries covering the full
5-year (1825-day) planning horizon.

Background:
  - sat↔sat costs are time-invariant within the same shell (no relative RAAN
    drift), and cycle well within 400 days for cross-inclination pairs — the
    existing 400-day wrapping remains valid.
  - depot↔sat costs drift at ~0.11 deg/day (depot at 600 km vs constellation
    at 550 km) and never complete a full relative RAAN cycle within 400 days.
    Wrapping at 400 days introduces ~44.7° geometry error per wrap.

Action:
  - Loads existing cost table (sat↔sat entries kept as-is).
  - Recomputes ALL depot↔sat and sat↔depot entries over [30 : TOF_STEP : T_END].
  - Merges new entries into the cost table and saves.

Prerequisites:
  - outputs/simulation.h5 must cover ≥ T_END days (init_script.jl propagates 5 yr).
  - outputs/cost_table.jld2 must exist (generated by gen_cost_table).

Run:
  julia --project=. -t auto extend_depot_cost_table.jl
"""

using JLD2, HDF5, Base.Threads, ProgressMeter

include("sim/propagator.jl")
include("demands/generate_demands.jl")
include("sol_utils.jl")
include("fuel_cost_calc/gen_cost_table.jl")

const TOF_STEP = 30.0    # days (must match existing cost table resolution)
const T_END    = 1825.0  # days — 5-year horizon
const MAX_TOF  = 730.0   # days — max transfer time (2 years, per mission design)

# ---------------------------------------------------------------------------
# Load existing tables
# ---------------------------------------------------------------------------

@info "Loading existing cost table …"
local CostTable, PhasingTimeTable
@load "outputs/cost_table.jld2"        CostTable
@load "outputs/phasing_time_table.jld2" PhasingTimeTable
@info "Existing entries" n=length(CostTable)

# ---------------------------------------------------------------------------
# Rebuild simulation handle (reads outputs/simulation.h5, no re-propagation)
# ---------------------------------------------------------------------------

@info "Loading simulation …"
sim = load_sim()

depots = findall(startswith("depot"), sim.names)
sats   = findall(startswith("sat"),   sim.names)
@info "Nodes" n_depots=length(depots) n_sats=length(sats)

plane_groups = get_plane_groups(sim, sats)
@info "Plane groups" n_planes=length(plane_groups)

# ---------------------------------------------------------------------------
# Build new depot↔sat keys over full [TOF_STEP : TOF_STEP : T_END] grid
# Only keep (dep, arr) pairs where arr - dep ≤ MAX_TOF
# ---------------------------------------------------------------------------

times_grid = collect(TOF_STEP:TOF_STEP:T_END)

depot_to_sat_keys = Tuple{Int,Int,Float64,Float64}[
    (depot, sat, dep, dep + tof)
    for tof in TOF_STEP:TOF_STEP:MAX_TOF
    for dep in times_grid
    if dep + tof <= T_END
    for sat   in sats
    for depot in depots
]

sat_to_depot_keys = Tuple{Int,Int,Float64,Float64}[
    (sat, depot, dep, dep + tof)
    for tof in TOF_STEP:TOF_STEP:MAX_TOF
    for dep in times_grid
    if dep + tof <= T_END
    for sat   in sats
    for depot in depots
]

# Filter to only NEW entries (not already in the existing cost table)
existing_keys = Set(keys(CostTable))
new_d2s = filter(k -> k ∉ existing_keys, depot_to_sat_keys)
new_s2d = filter(k -> k ∉ existing_keys, sat_to_depot_keys)

@info "New depot↔sat entries to compute" depot_to_sat=length(new_d2s) sat_to_depot=length(new_s2d)

# ---------------------------------------------------------------------------
# Compute new entries using existing fast builders
# ---------------------------------------------------------------------------

CT_d2s, PT_d2s = build_cost_table_depot_to_sat_fast(sim, new_d2s, plane_groups)
CT_s2d, PT_s2d = build_cost_table_sat_to_depot_fast(sim, new_s2d, plane_groups)

# ---------------------------------------------------------------------------
# Merge and save
# ---------------------------------------------------------------------------

@info "Merging …"
merge!(CostTable,        CT_d2s, CT_s2d)
merge!(PhasingTimeTable, PT_d2s, PT_s2d)

@info "Saving extended tables …" total_entries=length(CostTable)
@save "outputs/cost_table.jld2"         CostTable
@save "outputs/phasing_time_table.jld2" PhasingTimeTable
@info "Done. Extended depot↔sat entries to $(T_END)-day horizon."
