#!/usr/bin/env bash
# run_long_horizon_bcr.sh — BCR sweep on 5-year horizon demands.
# MDLS only, 1 trial, bcr_dvbudget 1000:1000:5000 m/s.
# Demand files must already exist in outputs/long_horizon_demands/
# (generated by: bash run_long_horizon.sh bcr_dvbudget  or  run_long_horizon.sh)

set -euo pipefail

JULIA="julia --project=. -t auto"
DEM_DIR="outputs/long_horizon_demands"
RES_DIR="outputs/long_horizon_results"
H5_FILE="outputs/long_horizon_results.h5"
TRIAL=1

mkdir -p "$RES_DIR"

# Generate demand file only if missing
dem="$DEM_DIR/bcr_mixed_5000_01.jld2"
if [ ! -f "$dem" ]; then
    echo "── Generating bcr_mixed demand files (400k demands, mixed fleet, 5-yr) ──"
    $JULIA generate_sensitivity_demands.jl --outdir="$DEM_DIR" bcr_mixed
fi

# Run MDLS for each budget level
for budget in 5000; do
    echo "── bcr_mixed=$budget  trial=$TRIAL (5-yr horizon, mixed fleet) ──"
    $JULIA run_mdls_trial.jl "bcr_mixed_${budget}" "$TRIAL" "$DEM_DIR" "$RES_DIR" "$budget" "$H5_FILE"
done

echo ""
echo "Done. Results in $H5_FILE"
echo "Run: python plot_bcr_architecture.py --h5 $H5_FILE"
